In [1]:
#Index ile Elemanlara Erişmek

In [2]:
import numpy as np

In [4]:
a = np.random.randint(10,size = 15)
a

array([7, 9, 2, 4, 0, 0, 8, 0, 5, 0, 3, 5, 1, 7, 0])

In [8]:
a[0]=1
a

array([1, 9, 2, 4, 0, 0, 8, 0, 5, 0, 3, 5, 1, 7, 0])

In [7]:
a[-1]

0

In [13]:
b = np.random.randint(10,size= (3,5)) 
b

array([[1, 0, 3, 7, 5],
       [0, 5, 8, 0, 7],
       [2, 4, 9, 9, 5]])

In [16]:
b[0,0],b[2,3]

(1, 9)

In [18]:
b[1,4] = 2.2
b

array([[1, 0, 3, 7, 5],
       [0, 5, 8, 0, 2],
       [2, 4, 9, 9, 5]])

In [19]:
#Array Alt Küme İşlemleri

In [21]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
a[:3]

array([20, 21, 22])

In [24]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [25]:
a[1::2]

array([21, 23, 25, 27, 29])

In [26]:
a[0::3]

array([20, 23, 26, 29])

In [27]:
#İki Boyutlu Slice İşlemleri

In [29]:
m = np.random.randint(10, size = (5,5))
m

array([[9, 3, 3, 9, 5],
       [1, 0, 7, 0, 6],
       [7, 6, 2, 6, 0],
       [0, 4, 8, 0, 5],
       [3, 2, 3, 4, 6]])

In [30]:
m[:,0] # Bütün satırları seç 0. sütunu getir

array([9, 1, 7, 0, 3])

In [36]:
m[[0],[3]]

array([9])

In [37]:
m[0:2,0:3]

array([[9, 3, 3],
       [1, 0, 7]])

In [41]:
m

array([[9, 3, 3, 9, 5],
       [1, 0, 7, 0, 6],
       [7, 6, 2, 6, 0],
       [0, 4, 8, 0, 5],
       [3, 2, 3, 4, 6]])

In [45]:
m[1:3,0:2]

array([[1, 0],
       [7, 6]])

In [46]:
#Alt Küme Üzerinde İşlem Yapmak

In [49]:
x = np.random.randint(10,size = (5,5))
x


array([[3, 5, 1, 5, 6],
       [1, 3, 2, 4, 9],
       [2, 5, 8, 9, 6],
       [9, 6, 5, 8, 0],
       [5, 8, 4, 5, 0]])

In [52]:
alt_x = x[0:3,0:2]
alt_x

array([[3, 5],
       [1, 3],
       [2, 5]])

In [54]:
alt_x[0,0] = 9999
alt_x[1,1] = 8888
alt_x

array([[9999,    5],
       [   1, 8888],
       [   2,    5]])

In [55]:
x

array([[9999,    5,    1,    5,    6],
       [   1, 8888,    2,    4,    9],
       [   2,    5,    8,    9,    6],
       [   9,    6,    5,    8,    0],
       [   5,    8,    4,    5,    0]])

In [57]:
alt_b = x[0:3,0:2].copy() # Ana array üzerinde bu şekilde değişiklik yapmaz. Faydası budur
alt_b

array([[9999,    5],
       [   1, 8888],
       [   2,    5]])

In [58]:
# Fancy Index İle Elemanlara Erişmek

In [59]:
v = np.arange(0,30,3) ## !!!!!!!!!!!!!!!!!!! Çok Önemli !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])