In [ ]:
## Numpy Özellikleri

In [3]:
import numpy as np

In [4]:
a=np.array([1,2,3,4,5])
type(a)

numpy.ndarray

In [9]:
b = np.array([3.74,4,2,13],dtype ="int") # Sabit tip olayı. Sadece tek tip tutar ve veri saklama maliyetini azaltır
b

array([ 3,  4,  2, 13])

In [ ]:
# Sıfırdan array oluşturma

In [11]:
np.zeros(10,dtype = "int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.ones((3,5),dtype = "int" ) 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
np.full((3,4),3,dtype = int)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [ ]:
#Doğrusal bir dizi

In [19]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [20]:
np.linspace(0,1,10) # Tek boyutlu 0 ile 1 arasında 10 tane eleman oluştur

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
np.random.normal(10,4,(3,4)) #Ortalama 10 standart sapma 4 3e 4 lük matris

array([[ 4.17211355,  6.12653164, 17.89518031,  9.15751495],
       [11.40683181,  7.39693891, 13.75402098,  2.27708724],
       [ 0.10518315,  5.07641317,  9.56101862, 12.86082695]])

In [27]:
np.random.randint(0,10 ,(3,4))

array([[9, 1, 9, 0],
       [2, 5, 0, 7],
       [6, 0, 5, 1]])

In [ ]:
# Numpy Array Özellikleri

* **ndim** : Boyut Sayısı 
* **shape** : Boyut Bilgisi
* **size** : Toplam Eleman Sayısı
* **dtype** : Array Veri Tipi

In [30]:
a=np.random.randint(10,size = 10) # 0'dan 10 rastgele int

In [32]:
a.ndim

1

In [33]:
a.shape

(10,)

In [34]:
a.size

10

In [35]:
a.dtype

dtype('int32')

In [39]:
b = np.random.randint(10, size = (3,5))
b

array([[1, 3, 8, 6, 5],
       [1, 7, 8, 1, 2],
       [8, 1, 4, 7, 1]])

In [40]:
b.ndim

2

In [41]:
b.shape

(3, 5)

In [42]:
b.size

15

In [43]:
b.dtype

dtype('int32')

In [ ]:
#Yeniden Şekillendirme

In [51]:
a=np.arange(1,300,35)
a

array([  1,  36,  71, 106, 141, 176, 211, 246, 281])

In [52]:
a.reshape((3,3))

array([[  1,  36,  71],
       [106, 141, 176],
       [211, 246, 281]])

In [54]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b=a.reshape((1,9))

In [59]:
b.ndim

2

In [ ]:
#Birleştirme İşlemleri

In [60]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [61]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [62]:
z = np.array([7,8,9])

In [63]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# İki Boyut

In [65]:
a = np.array([[1,2,3],
              [4,5,6]]) 
a

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [67]:
np.concatenate([a,a],axis = 1 ) # Eğer axis 0 sa satır bazında birleştirir 1 olursa yanyana sütun bazında birleştirme 

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
# Array Ayırma İşlemleri

In [69]:
x = np.array([1,2,3,99,99,3,2,1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [72]:
a,b,c = np.split(x,[3,5])


array([1, 2, 3])

In [73]:
# İki boyutlu ayırma

In [75]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [77]:
ust,alt =np.vsplit(m,[2])

In [78]:
z,v=np.hsplit(m,[2])

In [79]:
z

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])