In [1]:
#Matematiksel İşlemler

In [2]:
import numpy as np

In [3]:
v = np.array([1,2,3,4,5])

In [5]:
v-1 # Bütün Elemanlardan rakam çıkarma,çarpma bölme toplama işlemleri aynıdır.

array([0, 1, 2, 3, 4])

In [ ]:
#ufunc

In [7]:
np.subtract(v,-1) # Çıkarma

array([2, 3, 4, 5, 6])

In [9]:
np.add(v,2) # Toplama

array([3, 4, 5, 6, 7])

In [10]:
np.multiply(v,5) # Çarpma

array([ 5, 10, 15, 20, 25])

In [11]:
np.divide(v,4) # Bölme

array([0.25, 0.5 , 0.75, 1.  , 1.25])

In [14]:
np.power(v,3) # Üs Alma

array([  1,   8,  27,  64, 125], dtype=int32)

In [15]:
np.mod(v,2) # kalanını Bulma

array([1, 0, 1, 0, 1], dtype=int32)

In [16]:
np.absolute(np.array([-1,3,-5,-9])) # Mutlak Değer

array([1, 3, 5, 9])

In [17]:
np.sin(360)

0.9589157234143065

In [20]:
from math import pi

In [22]:
np.sin(pi)

1.2246467991473532e-16

In [23]:
v = np.array([1,2,3])

In [24]:
np.log(v) # İçindeki bütün elemanların logaritmasını alır

array([0.        , 0.69314718, 1.09861229])

In [26]:
np.log10(v) # 10 Tabanında

array([0.        , 0.30103   , 0.47712125])

In [27]:
?np